# Chiave del progetto su SonarQube
sonar.projectKey=Backgammon-gruppo11

# Attendere che SonarQube completi il controllo qualità prima di proseguire
sonar.qualitygate.wait=true

# Percorso delle sorgenti del progetto
sonar.sources=BackgammonGame/src

# Percorso dei test
sonar.tests=BackgammonGame/src/test

# Pattern per includere i file di test
sonar.test.inclusions=**/*.test.js,**/*.spec.js  # Aggiungi i pattern dei test, se necessario

# Percorso del report di copertura generato da Jest
sonar.javascript.lcov.reportPaths=BackgammonGame/coverage/lcov.info  # Verifica che il percorso del report sia corretto

# Altri parametri di configurazione
sonar.projectVersion=1.0
sonar.language=js
